apiVersion: v1
kind: Pod
metadata:
  name: ledger
spec:
  restartPolicy: Never
  containers:
    - name: ledger-container
      image: hub.pingcap.net/tiflash/schrodinger:{schrodinger_tag}
      command:
      - bash
      - "-c"
      - |
        export TIDB_SERVICE="{tidb_cluster_name}-tidb.{namespace}.svc:4000"
        /ledger -concurrency=80
      